# Generated by Django 4.2.3 on 2023-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='gender_type',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='inital_deposite_date',
            new_name='initial_deposite_date',
        ),
    ]
